### ISSUE TITLE
Lock Screen BUG

### ISSUE THREAD

**Issue by zMenta** [SolDoesTech/HyprV4#2]
Going to the lock screen, typing your password and unlocking it. If you lock the screen again you can just press any key to unlock it without using your password.

How to reproduce:
1. Lock the screen
2. Log in
3. Lock the screen again
4. Press any button

**Comment by JesseKoldewijn** [comment]
This mostly happend as far as I've noticed if you click any button fairly quickly right after locking. From what I can imagine its probably a cancel procedure.

**Comment by SolDoesTech** [comment]
As @JesseKoldewijn  stated, there is a 2 second grace period before the lock kicks in. You can change that if you like in ~/.config/swaylock/config the item is "grace=2" this can be updated to 1 or even 0.

**Comment by ZethJack** [comment]
I thought I had similar issue where swaylock would seemingly "crash" upon pressing any key. Turns out that it was actually this grace period feature.
When I want to lock my computer, I deliberately go through the menu options, or hit corresponding hotkey combination. Adding a two second delay within which you can abort the process of locking down the computer doesn't really make sense and instead it makes the user think that the utility is broken.
