### ISSUE TITLE
same problem 53 

### ISSUE THREAD

**Issue by bigpennybanks** [SolDoesTech/HyprV4#54]
just did a freshinstall and ran the script.  cannot get a confirm on the password i believe, it doesnt say specifically so could be a bug?

ok i got in on the tty but not in login. i think it maybe becasue the log in is auto capitalized? is there a way i can try without the auto cap? maybe something else but pw is correct forsure

ok so i made another user, could not log in but am told log in failed. so the original user login seems to be a bug not a incorrect pw. still stuck

**Comment by TeddyHuang-00** [comment]
Might be a dup to https://github.com/SolDoesTech/HyprV4/issues/53 . The problem is most likely not with your login process (you can try enter a wrong password to see the difference), it's rather something have to do with hyprland or something in the DE. Please join our dicussion there if you have the same issue.
